# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: convex_keys.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'convex_keys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onvex_keys.proto\x12\x0b\x63onvex_keys\x1a\x1bgoogle/protobuf/empty.proto\"\xab\x01\n\x08\x41\x64minKey\x12\x1a\n\rinstance_name\x18\x01 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x08issued_s\x18\x02 \x01(\x04\x12\x13\n\tmember_id\x18\x03 \x01(\x04H\x00\x12(\n\x06system\x18\x04 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12\x14\n\x0cis_read_only\x18\x05 \x01(\x08\x42\n\n\x08identityB\x10\n\x0e_instance_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convex_keys_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADMINKEY']._serialized_start=64
  _globals['_ADMINKEY']._serialized_end=235
# @@protoc_insertion_point(module_scope)
